### ISSUE TITLE
segfault in cluster run ( on run 2 ), in mbulk_size_el::get_next_mbulk at protocol.h

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabs/memtier_benchmark#116]
## steps to reproduce 

```
memtier_benchmark -n 10 --cluster-mode -p 20000 --run-count 3
```

## segfault backtrace
```
Thread 6 "memtier_benchma" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeffff700 (LWP 27658)]
0x000055555558a9bf in mbulk_size_el::get_next_mbulk (this=0x7fffe8001a50) at protocol.h:75
75	            if (next->bulks_count == 0) {
(gdb) info registers
rax            0x30	48
rbx            0x7fffe8001b10	140737085709072
rcx            0x3	3
rdx            0x0	0
rsi            0x7fffe80008d0	140737085704400
rdi            0x7fffe8001a50	140737085708880
rbp            0x7fffefffec20	0x7fffefffec20
rsp            0x7fffefffec20	0x7fffefffec20
r8             0x7fffe80008d0	140737085704400
r9             0x0	0
r10            0x7fffe80008d0	140737085704400
r11            0x0	0
r12            0xe	14
r13            0x555555adbbc0	93824998030272
r14            0x7ffff7995d40	140737347411264
r15            0xe	14
rip            0x55555558a9bf	0x55555558a9bf <mbulk_size_el::get_next_mbulk()+27>
eflags         0x10206	[ PF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) bt
#0  0x000055555558a9bf in mbulk_size_el::get_next_mbulk (this=0x7fffe8001a50) at protocol.h:75
#1  0x0000555555588934 in redis_protocol::parse_response (this=0x55555654be20) at protocol.cpp:561
#2  0x0000555555571be8 in shard_connection::process_response (this=0x55555654bd90) at shard_connection.cpp:379
#3  0x0000555555570b84 in cluster_client_read_handler (bev=0x555555adb9a0, ctx=0x55555654bd90) at shard_connection.cpp:64
#4  0x00007ffff7995e32 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#5  0x00007ffff799b8f8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#6  0x00007ffff799c33f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#7  0x0000555555569dd7 in client_group::run (this=0x5555557c7140) at client.cpp:587
#8  0x000055555555cc08 in cg_thread_start (t=0x555555e888b0) at memtier_benchmark.cpp:996
#9  0x00007ffff700d6db in start_thread (arg=0x7fffeffff700) at pthread_create.c:463
#10 0x00007ffff63a088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Buffer0x7cd** [comment]
+1
