### ISSUE TITLE
Segfault when passing --unix-socket

### ISSUE THREAD

**Issue by simon-shopify** [RedisLabs/memtier_benchmark#49]
When I invoke `memtier_benchmark` with the `--unix-socket` option, it segfaults when the client is trying to connect to Redis. For some reason, it tries to [invoke `get_connection_info`](https://github.com/RedisLabs/memtier_benchmark/blob/fdd22d8b17bcd27db3a20fef9af2d6f70f4c95d9/client.cpp#L199) on the `server_addr`, but it is `null`. Here is the full backtrace:
```
#0  0x00007ffff7dc4365 in pthread_mutex_lock () from /lib/ld-musl-x86_64.so.1
#1  0x000055555556b716 in server_addr::get_connect_info (this=0x0, 
    ci=ci@entry=0x7fffffffd190) at config_types.cpp:234
#2  0x000055555555ca6d in client::connect (this=0x7ffff7b27d60)
    at client.cpp:199
#3  0x000055555555ca01 in client::prepare (this=<optimized out>)
    at client.cpp:344
#4  0x000055555555d52e in client_group::prepare (this=0x7ffff7d71fa0)
    at client.cpp:539
#5  0x000055555555b259 in cg_thread::prepare (this=0x7ffff7d71ea0, 
    this=0x7ffff7d71ea0) at memtier_benchmark.cpp:790
#6  run_benchmark (run_id=1, cfg=0x7fffffffe4f0, obj_gen=0x555555788c40)
    at memtier_benchmark.cpp:842
#7  0x0000555555559c5c in main (argc=<optimized out>, argv=<optimized out>)
    at memtier_benchmark.cpp:1160
```

**Comment by yaacovhazan-Redislabs** [comment]
fixed in PR - 'fix unix socket connection #55'
